title: Host delegation settings changed for potential abuse (Rubeus)
description: Detects scenarios where an attacker modifies host delegation settings for privilege escalation.
references:
- https://github.com/mdecrevoisier/EVTX-to-MITRE-Attack/tree/master/TA0003-Persistence/T1098.xxx-Account%20manipulation
- https://dirkjanm.io/krbrelayx-unconstrained-delegation-abuse-toolkit/
- https://www.alsid.com/crb_article/kerberos-delegation/
- https://www.harmj0y.net/blog/activedirectory/s4u2pwnage/
- https://shenaniganslabs.io/2019/01/28/Wagging-the-Dog.html
- https://www.ired.team/offensive-security-experiments/active-directory-kerberos-abuse/abusing-kerberos-constrained-delegation
- https://www.guidepointsecurity.com/delegating-like-a-boss-abusing-kerberos-delegation-in-active-directory/
- https://stealthbits.com/blog/what-is-kerberos-delegation-an-overview-of-kerberos-delegation/
tags:
- attack.persistence
- attack.t1098
author: mdecrevoisier
status: experimental
logsource:
  product: windows
  service: security
detection:
  
  # UNCONSTRAINED DELEGATION | delegation to any service, Kerberos only
  selection_1_unconstrained:
    EventID: 4742
    UserAccountControl: '%%2093' # Enable option "Trust this computer for delegation to any service (Kerberos only)"
  
  # CONSTRAINED DELEGATION | delegation to specified service, any protocol
  selection_2_constrained:
    EventID: 4742
    UserAccountControl: '%%2098' # Enable option "Approved for authenticated delegation"
  filter_2:
    AllowedToDelegateTo: '-' # Can be: ""cifs/srv01 cifs/srv02.offsec.lan dcom/dc03..."
  condition: (selection_2 and not filter_2)

  # CONSTRAINED DELEGATION | delegation to specified service, Kerberos only
  selection_3_constrained:
    EventID: 4742
    UserAccountControl: '-'  # Avoid duplicate with with selection 2
  filter_3:
    AllowedToDelegateTo: '-' # Can be: ""cifs/srv01 cifs/srv02.offsec.lan dcom/dc03..."
  condition: (selection_3 and not filter_3)

  condition: selection_1_unconstrained or (selection_2_constrained and not filter_2) or (selection_3_constrained and not filter_3)
falsepositives:
- Rare administrator modifying host delegation settings
level: high